name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Configure AWS Credentials with keys in github secrets
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAQISRN6U2LN3HPXPW
        aws-secret-access-key: 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
        aws-region: us-east-1
    
    - name: setup DVC to pull data
      uses: iterative/setup-dvc@v1
    
    - name: DVC Init
      run : |
        dvc init -f
    
    - name: DVC Pull
      run : |
        dvc pull
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install flake and pytest dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install pytest
    - name: Run unit tests
      run: |
        python -m pytest
    - name: Lint with flake8 
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
